#!/usr/bin/env python3
"""
Log left and right brake sensor ADC values and calibrated force values to one CSV.

Hardware mapping requested:
    left brake sensor  -> I2C register 0x17
    right brake sensor -> I2C register 0x14

Calibration model:
    force_g = slope_g_per_adc * adc + intercept_g

By default, this script uses the fitted coefficients from
Calibration_Right_&_Left_12May.ods / Sheet1. You can also pass a JSON calibration
file generated by fit_brake_sensor_calibration.py:
    python3 log_brake_sensors_force_to_csv.py --calibration-json brake_sensor_calibration.json
"""

import argparse
import csv
import json
import math
import os
import time
from typing import Dict, List, Optional

import smbus

# -------- I2C config --------
I2C_BUS = 1
I2C_ADDR = 0x24
LEFT_REG = 0x17
RIGHT_REG = 0x14

# -------- logging config --------
SAMPLE_PERIOD_S = 0.1  # 10 Hz
FLUSH_ROWS = 500

# Fitted from Calibration_Right_&_Left_12May.ods, Sheet1:
#   left:  force_g = 5.9092229449 * adc - 321.9034713174
#   right: force_g = 6.9068825517 * adc - 341.0880127929
DEFAULT_CALIBRATION = {
    "left": {
        "slope_g_per_adc": 5.9092229449,
        "intercept_g": -321.9034713174,
    },
    "right": {
        "slope_g_per_adc": 6.9068825517,
        "intercept_g": -341.0880127929,
    },
}

out_dir = os.path.expanduser("~/bikelab_interface_logs")
ts = time.strftime("%Y%m%d_%H%M%S", time.localtime())
DEFAULT_OUT_CSV = os.path.join(out_dir, f"brake_sensors_force_{ts}.csv")


def now_unix_ns() -> int:
    return time.time_ns()


def g_to_newton(force_g: float) -> float:
    return force_g * 0.00980665


def load_calibration(json_path: Optional[str]) -> Dict[str, Dict[str, float]]:
    """Load calibration JSON, or fall back to embedded fitted coefficients."""
    if not json_path:
        return DEFAULT_CALIBRATION

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # JSON from fit_brake_sensor_calibration.py has coefficients under sensors.left/right.
    sensors = data.get("sensors", data)
    cal = {}
    for side in ("left", "right"):
        if side not in sensors:
            raise ValueError(f"Calibration JSON missing '{side}' sensor.")
        cal[side] = {
            "slope_g_per_adc": float(sensors[side]["slope_g_per_adc"]),
            "intercept_g": float(sensors[side]["intercept_g"]),
        }
    return cal


def adc_to_force_g(adc: float, fit: Dict[str, float], clamp_min_zero: bool = True) -> float:
    """Convert ADC to force in grams using a linear fit."""
    force_g = fit["slope_g_per_adc"] * float(adc) + fit["intercept_g"]
    if clamp_min_zero and force_g < 0:
        return 0.0
    return force_g


class BrakeSensorForceLogger:
    def __init__(self, out_csv: str, calibration: Dict[str, Dict[str, float]], flush_rows: int = 500):
        self.out_csv = out_csv
        self.calibration = calibration
        self.flush_rows = int(flush_rows)

        os.makedirs(os.path.dirname(out_csv) or ".", exist_ok=True)

        self.bus = smbus.SMBus(I2C_BUS)
        self.rows: List[list] = []
        self._open_csv()

    def _open_csv(self) -> None:
        new_file = not os.path.exists(self.out_csv) or os.path.getsize(self.out_csv) == 0
        self.f = open(self.out_csv, "a", newline="")
        self.w = csv.writer(self.f)
        if new_file:
            self.w.writerow([
                "t_unix_ns",
                "ok_left",
                "left_adc_raw",
                "left_force_g",
                "left_force_n",
                "left_error",
                "ok_right",
                "right_adc_raw",
                "right_force_g",
                "right_force_n",
                "right_error",
            ])
            self.f.flush()

    def read_adc(self, reg: int) -> int:
        """Keep the same read style as the original script."""
        self.bus.write_byte(I2C_ADDR, reg)
        raw = self.bus.read_word_data(I2C_ADDR, reg)
        return int(raw)

    def read_one_sensor(self, side: str, reg: int):
        try:
            adc = self.read_adc(reg)
            force_g = adc_to_force_g(adc, self.calibration[side], clamp_min_zero=True)
            force_n = g_to_newton(force_g)
            return 1, adc, force_g, force_n, ""
        except Exception as e:
            return 0, math.nan, math.nan, math.nan, str(e)

    def log_once(self) -> None:
        t = now_unix_ns()

        left_ok, left_adc, left_force_g, left_force_n, left_err = self.read_one_sensor("left", LEFT_REG)
        right_ok, right_adc, right_force_g, right_force_n, right_err = self.read_one_sensor("right", RIGHT_REG)

        row = [
            t,
            left_ok,
            left_adc,
            left_force_g,
            left_force_n,
            left_err,
            right_ok,
            right_adc,
            right_force_g,
            right_force_n,
            right_err,
        ]
        self.rows.append(row)

        print(
            f"left adc={left_adc}, force_g={left_force_g:.2f} | "
            f"right adc={right_adc}, force_g={right_force_g:.2f}"
        )

        if len(self.rows) >= self.flush_rows:
            self.flush()

    def flush(self) -> None:
        if not self.rows:
            return
        self.w.writerows(self.rows)
        self.f.flush()
        self.rows.clear()

    def close(self) -> None:
        try:
            self.flush()
        finally:
            try:
                self.f.close()
            except Exception:
                pass
            try:
                self.bus.close()
            except Exception:
                pass

    def run(self, period_s: float = SAMPLE_PERIOD_S) -> None:
        print(f"[INFO] Logging brake sensor ADC and force to {self.out_csv}")
        print(f"[INFO] Left register: 0x{LEFT_REG:02X}; right register: 0x{RIGHT_REG:02X}")
        print(f"[INFO] Sampling period: {period_s}s, flush every {self.flush_rows} rows")
        print(
            "[INFO] Calibration: "
            f"left force_g={self.calibration['left']['slope_g_per_adc']:.10f}*adc"
            f"{self.calibration['left']['intercept_g']:+.10f}; "
            f"right force_g={self.calibration['right']['slope_g_per_adc']:.10f}*adc"
            f"{self.calibration['right']['intercept_g']:+.10f}"
        )

        next_t = time.time()
        try:
            while True:
                self.log_once()
                next_t += period_s
                sleep_s = next_t - time.time()
                if sleep_s > 0:
                    time.sleep(sleep_s)
                else:
                    next_t = time.time()
        except KeyboardInterrupt:
            print("\n[INFO] Ctrl-C received. Flushing and exiting...")
        finally:
            self.close()
            print("[INFO] Done.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Log two brake sensors ADC and calibrated force to CSV.")
    parser.add_argument("--out-csv", default=DEFAULT_OUT_CSV)
    parser.add_argument("--calibration-json", default=None, help="Optional JSON from fit_brake_sensor_calibration.py")
    parser.add_argument("--period", type=float, default=SAMPLE_PERIOD_S)
    parser.add_argument("--flush-rows", type=int, default=FLUSH_ROWS)
    args = parser.parse_args()

    calibration = load_calibration(args.calibration_json)
    logger = BrakeSensorForceLogger(out_csv=args.out_csv, calibration=calibration, flush_rows=args.flush_rows)
    logger.run(period_s=args.period)


if __name__ == "__main__":
    main()
